{
 "title": "ec2_prometheus",
 "tags": [
  "prometheus",
  "ec2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "name", "label": "name", "query": { "query": "label_values(ec2_name)" } }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", ec2_name=\"$name\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{ec2_name=\"$name\"}) * 100 / count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{ec2_name=\"$name\"} / node_memory_MemTotal_bytes{ec2_name=\"$name\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{ec2_name=\"$name\"} - node_memory_SwapFree_bytes{ec2_name=\"$name\"}) / (node_memory_SwapTotal_bytes{ec2_name=\"$name\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{ec2_name=\"$name\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{ec2_name=\"$name\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{ec2_name=\"$name\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{ec2_name=\"$name\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{ec2_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{ec2_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{ec2_name=\"$name\"} - node_boot_time_seconds{ec2_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time usage split by state, normalized across all CPU cores",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"system\", ec2_name=\"$name\"}[$__rate_interval])\n)\n/\nscalar(\n  count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu))\n)\n",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"user\", ec2_name=\"$name\"}[$__rate_interval])\n)\n/\nscalar(\n  count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu))\n)\n",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", ec2_name=\"$name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_guest_seconds_total{ec2_name=\"$name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{ec2_name=\"$name\"}[$__rate_interval]))) > 0",
     "legendFormat": "Guest CPU usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Breakdown of physical memory and swap usage. Hardware-detected memory errors are also displayed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{ec2_name=\"$name\"} - node_memory_MemFree_bytes{ec2_name=\"$name\"} - node_memory_Buffers_bytes{ec2_name=\"$name\"} - node_memory_Cached_bytes{ec2_name=\"$name\"} - node_memory_Slab_bytes{ec2_name=\"$name\"} - node_memory_PageTables_bytes{ec2_name=\"$name\"} - node_memory_SwapCached_bytes{ec2_name=\"$name\"}\n",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{ec2_name=\"$name\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{ec2_name=\"$name\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{ec2_name=\"$name\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{ec2_name=\"$name\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{ec2_name=\"$name\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{ec2_name=\"$name\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{ec2_name=\"$name\"} - node_memory_SwapFree_bytes{ec2_name=\"$name\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{ec2_name=\"$name\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "CPU time usage split by state, normalized across all CPU cores",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_load5{ec2_name=\"$name\"}\n",
     "legendFormat": "Load 5"
    }
   ]
  },
  { "title": "EBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Filesystem Space Available",
   "type": "timeseries",
   "description": "Amount of available disk space per mounted filesystem, excluding rootfs. Based on block availability to non-root users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{ec2_name=\"$name\", mountpoint!~\"^/(run.*|boot.*)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "timeseries",
   "description": "Disk usage (used = total - available) per mountpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{ec2_name=\"$name\"} - node_filesystem_avail_bytes{ec2_name=\"$name\", mountpoint!~\"^/(run.*|boot.*)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "description": "Disk I/O operations per second for each device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Percentage of time the disk was actively processing I/O operations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{ec2_name=\"$name\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "System Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "System load average over 1, 5, and 15 minutes. Reflects the number of active or waiting processes. Values above CPU core count may indicate overload",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{ec2_name=\"$name\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{ec2_name=\"$name\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{ec2_name=\"$name\"}",
     "legendFormat": "Load 15m"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{ec2_name=\"$name\"}) by (cpu))",
     "legendFormat": "CPU Core Count"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "description": "Rate of Out-of-Memory (OOM) kill events. A non-zero value indicates the kernel has terminated one or more processes due to memory exhaustion",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "OOM Kills"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "description": "Number of network packets received and transmitted per second, by interface.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "description": "Rate of packet-level errors for each network interface. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "description": "Rate of dropped packets per network interface. Receive drops can indicate buffer overflow or driver issues; transmit drops may result from outbound congestion or queuing limits",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{ec2_name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  }
 ]
}